# Site settings
title: Skrimmage
email: Danny@Skrimmage.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.skrimmage.com" # the base hostname & protocol for your site

twitter_username: SkrimmageForum
github_username: Skrimmage

# Build settings
markdown: kramdown
